### PR TITLE
Remove most uses of boost

### PR DESCRIPTION
**Pull request by Qudix**
I removed most uses of boost's `iterator_interface`. This needs testing. I haven't touched `BSTArray` yet as that's the most complicated one and I'm unsure how to go about it.

- [x] BSTBTree
- [x] BSTHashMap
- [x] BSTObjectArena
- [x] BSSimpleList
  - [x] counted_function_iterator
- [x] NiTArray
  - [x] NiTObjectArray
  - [x] NiTPrimitiveArray

### CODE REVIEW

**Comment by alandtse** [comment]
Perhaps check with SSE and how it was removed out from there?

**Comment by Qudix** [comment]
The SSE version never had boost added to it. I don't understand enough about `BSTArray` to make the proper changes to it. I might just leave it for someone else to tackle.

**Comment by alandtse** [comment]
This isn't something that code review will really help with. Did you do some basic testing that the containers seem to work?

**Comment by Qudix** [comment]
Not extensively, most of these containers don't have constructors defined so I can't make automatic tests for them. Besides BSTHashMap, the only way to test them is to grab an already constructed one from the game and iterate over its data. This involves making a plugin.

**Comment by alandtse** [comment]
If you've done some basic testing, I'd be ok with merging. My concern is if this was completely blind since it's not a fix or feature but more some refactoring. That would mean holding it out until some testing could be run since it's a potentially significant change. 

That said, given some testing I'll merge it in.

**Comment by Qudix** [comment]
Ok, I tested some more using data from the game where available and all of the iteration scenarios I know of still work. I can't verify everything else as I can't come up with more advanced examples, and the lack of constructors limits things.

**Pull request merged**
